version: '3.8'

services:
  app:
    build:
      context: .              # Dockerfile 现在在根目录
      dockerfile: Dockerfile  # 可省略，默认就是这个名字
    image: likanug/anitrack:1.0.0      # ⬅️ 指定构建后的镜像名和版本
    container_name: AniTrack
    working_dir: /app
    command: python main.py
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1